package src;
public class MenuPrices {
    // Shows menu with prices included
    String[] displayMenuPrices = {
            "BUFFALO CHICKEN, RED ONION, GORGONZOLA CRUMBLE  (Sm $15.75 Lg $25.00)",
            "CAPICOLA, PINEAPPLE, HOT-HONEY || (Sm $15.75 Lg $25.00)",
            "CHEESE (RED SAUCE) || (Sm $13.25 Lg $18.75)",
            "CUP & CHAR PEPPERONI (RED SAUCE) || (Sm $14.50 Lg $21.00)",
            "FRESH MUSHROOM, BROCCOLI, RED PEPPERS, SWEET CHILI SAUCE || (Sm $15.50 Lg $24.50)",
            "FRESH MUSHROOM, ROASTED GARLIC, GORGONZOLA CRUMBLE, SIDE OF BUFFALO SAUCE || (Sm $15.50 Lg $24.50)",
            "MAINE BLUEBERRIES, RICOTTA, ROASTED SHALLOT, LEMON ZEST || (Sm $15.50 Lg $24.50)",
            "MARGHERITA: TOMATO, BASIL, BALSAMIC REDUCTION || (Sm $15.50 Lg $24.50)",
            "MASHED POTATO, BACON, SHALLOT, SOUR CREAM CHIVE DRIZZLE || (Sm $15.75 Lg $25.00)",
            "MASHED POTATO, SPINACH, SHALLOT, ROASTED RED PEPPERS, BROCCOLI || (Sm $15.50 Lg $24.50)",
            "PEACHES, BALSAMIC REDUCTION, GOAT CHEESE, BASIL || (Sm $15.50 Lg $24.50)",
            "PEPPERONI, GROUND BEEF, CHERRY TOMATO, RED ONION, DONAIR SAUCE (RED SAUCE) || (Sm $15.75 Lg $25.00)",
            "ROASTED CHICKEN, PESTO || (Sm $14.75 Lg $23.50)",
            "SAUSAGE, FETA, BANANA PEPPER || (Sm $15.75 Lg $25.00)",
            "SAUSAGE, FRESH MUSHROOM, RED ONION (RED SAUCE) || (Sm $15.75 Lg $25.00)",
            "SMOKED BBQ PULLED PORK, FUJI APPLE, RED ONION || (Sm $15.75 Lg $25.00)",
            "SMOKED PULLED PORK, GOUDA, MAC & CHEESE, JALAPENO CORNBREAD || (Sm $15.75 Lg $25.00)",
            "SPINACH, FRESH TOMATO, GOAT CHEESE (RED SAUCE) || (Sm $15.50 Lg $24.50)",
            "SPINACH, RICOTTA, GARLIC (RED SAUCE) || (Sm $15.50 Lg $24.50)",
            "STRAWBERRY, BACON, HOT HONEY CHICKEN || (Sm $15.75 Lg $25.00)",
            "SWEET POTATO, GOAT CHEESE, HONEY DRIZZLE || (Sm $15.50 Lg $24.50)",
            "TOMATO, BASIL, PESTO || (Sm $14.74 Lg $23.50)",
    };
}
