package src;
public class Menu {
    // Shows menu (with prices omitted)
    String[] displayMenu = {
            "BUFFALO CHICKEN, RED ONION, GORGONZOLA",
            "CAPICOLA, PINEAPPLE, HOT-HONEY",
            "CHEESE (RED SAUCE)",
            "CUP & CHAR PEPPERONI (RED SAUCE)",
            "FRESH MUSHROOM, BROCCOLI, RED PEPPERS, SWEET CHILI SAUCE",
            "FRESH MUSHROOM, ROASTED GARLIC, GORGONZOLA CRUMBLE, SIDE OF BUFFALO SAUCE",
            "MAINE BLUEBERRIES, RICOTTA, ROASTED SHALLOT, LEMON ZEST",
            "MARGHERITA: TOMATO, BASIL, BALSAMIC REDUCTION",
            "MASHED POTATO, BACON, SHALLOT, SOUR CREAM CHIVE DRIZZLE",
            "MASHED POTATO, SPINACH, SHALLOT, ROASTED RED PEPPERS, BROCCOLI",
            "PEACHES, BALSAMIC REDUCTION, GOAT CHEESE, BASIL",
            "PEPPERONI, GROUND BEEF, CHERRY TOMATO, RED ONION, DONAIR SAUCE",
            "ROASTED CHICKEN, PESTO",
            "SAUSAGE, FETA, BANANA PEPPER",
            "SAUSAGE, FRESH MUSHROOM, RED ONION (RED SAUCE)",
            "SMOKED BBQ PULLED PORK, FUJI APPLE, RED ONION",
            "SMOKED PULLED PORK, GOUDA, MAC & CHEESE, JALAPENO CORNBREAD",
            "SPINACH, FRESH TOMATO, GOAT CHEESE (RED SAUCE)",
            "SPINACH, RICOTTA, GARLIC (RED SAUCE)",
            "STRAWBERRY, BACON, HOT HONEY CHICKEN",
            "SWEET POTATO, GOAT CHEESE, HONEY DRIZZLE",
            "TOMATO, BASIL, PESTO",
    };
}